<?php
// Sample data (replace with DB query in real app)
$requests = [
    [
        'id' => 1,
        'name' => 'Juan Dela Cruz',
        'requested_by' => 'Maria Santos',
        'status' => 'Pending',
        'generated_by' => 'N/A',
        'approved_by' => 'N/A',
        'date_requested' => '2025-06-01',
        'date_approved' => 'N/A',
    ],
    [
        'id' => 2,
        'name' => 'Ana Reyes',
        'requested_by' => 'Carlos Reyes',
        'status' => 'Approved',
        'generated_by' => 'AdminUser1',
        'approved_by' => 'Father Jose',
        'date_requested' => '2025-05-29',
        'date_approved' => '2025-06-02',
    ],
];
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Certificate Requests - Admin</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">

    <!-- SB Admin 2 Theme -->
    <link href="https://cdn.jsdelivr.net/gh/StartBootstrap/startbootstrap-sb-admin-2/css/sb-admin-2.min.css" rel="stylesheet">
</head>

<body id="page-top">
<div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
    <a class="sidebar-brand d-flex align-items-center justify-content-center mt-3" href="#">
    <div class="sidebar-brand-icon mr-2">
        <i class="fas fa-church"></i>
    </div>
    <div class="d-flex flex-column text-white text-center">
        <div class="font-weight-bold">OUR LADY OF</div>
        <div class="font-weight-bold">LIGHT PARISH</div>
        <div class="small">LOON,BOHOL</div>
    </div>
</a>


        <hr class="sidebar-divider my-3">

        <li class="nav-item active">
            <a class="nav-link" href="#"><i class="fas fa-fw fa-file-alt"></i><span>Certificate Requests</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="approved_certificates.php">
        <i class="fas fa-fw fa-check"></i><span>Approved Certificates</span></a>
        </li>

      <li class="nav-item">
    <a class="nav-link" href="certificate_tracking.php">
        <i class="fas fa-map-marker-alt"></i><span>Track Requests</span>
    </a>
</li>

        <li class="nav-item">
            <a class="nav-link" href="#"><i class="fas fa-fw fa-cogs"></i><span>Settings</span></a>
        </li>

        <hr class="sidebar-divider d-none d-md-block">
    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">
        <div id="content">

            <!-- Topbar -->
            <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
    <h5 class="ml-3 font-weight-bold text-primary">Certificate Requests</h5>
    <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle d-flex align-items-center" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 font-weight-bold text-gray-800">Admin</span>
                <i class="fas fa-user fa-fw"></i>
            </a>
            
        </li>
    </ul>
</nav>


            <!-- Main Content -->
            <div class="container-fluid">
                <div class="card shadow mb-4">
                    <div class="card-header py-3 bg-primary text-white">
                        <h6 class="m-0 font-weight-bold">Pending and Approved Requests</h6>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered text-center">
                                <thead class="thead-dark">
                                <tr>
                                    <th>Request ID</th>
                                    <th>Child's Name</th>
                                    <th>Requested By</th>
                                    <th>Status</th>
                                    <th>Date Requested</th>
                                    <th>Date Approved</th>
                                    <th>Generated By</th>
                                    <th>Approved By</th>
                                    <th>Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php foreach ($requests as $req): ?>
                                    <tr>
                                        <td><?= $req['id'] ?></td>
                                        <td><?= $req['name'] ?></td>
                                        <td><?= $req['requested_by'] ?></td>
                                        <td>
                                            <?php if ($req['status'] === 'Pending'): ?>
                                                <span class="badge badge-warning">Pending</span>
                                            <?php else: ?>
                                                <span class="badge badge-success">Approved</span>
                                            <?php endif; ?>
                                        </td>
                                        <td><?= $req['date_requested'] ?></td>
                                        <td><?= $req['date_approved'] ?></td>
                                        <td><?= $req['generated_by'] ?></td>
                                        <td><?= $req['approved_by'] ?></td>
                                        <td>
                                            <!-- Actions Column: Buttons for View, Approve, and Generate -->
                                            <div class="d-flex flex-column align-items-stretch">
                                                <!-- View button (track request) -->
                                                <a href="track_request.php?id=<?= $req['id'] ?>" class="btn btn-sm btn-secondary mb-2"> View
                                                </a>

                                                <?php if ($req['status'] == 'Pending'): ?>
                                                    <!-- Approve button -->
                                                    <button class="btn btn-sm btn-primary mb-2"> Approve</button>

                                                    <!-- Generate button -->
                                                    <a href="generate.php?id=<?= $req['id'] ?>" class="btn btn-sm btn-info mb-2"> Generate
                                                    </a>
                                                <?php else: ?>
                                                    <span class="text-muted">No actions</span>
                                                <?php endif; ?>
                                            </div>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End Main Content -->

        </div>

        <!-- Footer -->
        <footer class="sticky-footer bg-white">
            <div class="container my-auto text-center">
                <span class="text-muted">© <?= date('Y') ?> Baptism Certificate System</span>
            </div>
        </footer>

    </div>
</div>

<!-- JS Files -->
<script src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/gh/StartBootstrap/startbootstrap-sb-admin-2/js/sb-admin-2.min.js"></script>
</body>
</html>
