<?php
// Simulated approved requests with delivery status
$requests = [
    1 => [
        'name' => 'Juan Dela Cruz',
        'requested_by' => 'Maria Santos',
        'status' => 'Approved',
        'generated_by' => 'AdminUser1',
        'approved_by' => 'Father Jose',
        'date_requested' => '2025-06-01',
        'date_approved' => '2025-06-03',
        'delivery_status' => 'Delivered'
    ],
    2 => [
        'name' => 'Ana Reyes',
        'requested_by' => 'Carlos Reyes',
        'status' => 'Approved',
        'generated_by' => 'AdminUser1',
        'approved_by' => 'Father Jose',
        'date_requested' => '2025-05-29',
        'date_approved' => '2025-06-02',
        'delivery_status' => 'Received'
    ]
];

// Get request ID from URL and ensure it's an integer
$requestId = filter_input(INPUT_GET, 'id', FILTER_VALIDATE_INT);
$request = null;

if ($requestId !== false && isset($requests[$requestId])) {
    $request = $requests[$requestId];
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Track Certificate Status</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
</head>
<body class="bg-light">

<div class="container mt-5">
    <a href="tracking.php" class="btn btn-secondary mb-4">
        <i class="fas fa-arrow-left"></i> Back to Approved Certificates
    </a>

    <?php if ($request): ?>
        <div class="card shadow">
            <div class="card-header bg-primary text-white">
                <h5 class="mb-0">Tracking Certificate for <?= htmlspecialchars($request['name']) ?></h5>
            </div>
            <div class="card-body">
                <ul class="list-group mb-4">
                    <li class="list-group-item"><strong>Requested By:</strong> <?= $request['requested_by'] ?></li>
                    <li class="list-group-item"><strong>Status:</strong> <?= $request['status'] ?></li>
                    <li class="list-group-item"><strong>Date Requested:</strong> <?= $request['date_requested'] ?></li>
                    <li class="list-group-item"><strong>Date Approved:</strong> <?= $request['date_approved'] ?></li>
                    <li class="list-group-item"><strong>Generated By:</strong> <?= $request['generated_by'] ?></li>
                    <li class="list-group-item"><strong>Approved By:</strong> <?= $request['approved_by'] ?></li>
                    <li class="list-group-item">
                        <strong>Delivery Status:</strong>
                        <?php
                        $status = strtolower($request['delivery_status']);
                        switch ($status) {
                            case 'delivered':
                                echo '<span class="badge badge-warning"><i class="fas fa-truck"></i> Delivered (Awaiting Pickup)</span>';
                                break;
                            case 'received':
                                echo '<span class="badge badge-success"><i class="fas fa-check-circle"></i> Received by Requester</span>';
                                break;
                            default:
                                echo '<span class="badge badge-secondary"><i class="fas fa-clock"></i> Processing</span>';
                        }
                        ?>
                    </li>
                </ul>

                <!-- Optional progress indicator -->
                <h6>Status Progress</h6>
                <div class="progress mb-3" style="height: 25px;">
                    <?php
                    $progress = match ($status) {
                        'processing' => 25,
                        'delivered'  => 75,
                        'received'   => 100,
                        default      => 0
                    };
                    ?>
                    <div class="progress-bar
                        <?= $progress == 100 ? 'bg-success' : ($progress >= 75 ? 'bg-warning' : 'bg-secondary') ?>"
                        role="progressbar"
                        style="width: <?= $progress ?>%">
                        <?= $progress ?>%
                    </div>
                </div>
            </div>
        </div>
    <?php else: ?>
        <div class="alert alert-danger">Request not found. Please check the link or go back.</div>
    <?php endif; ?>
</div>

</body>
</html>
